spring.application.name=userservice
server.port=8081
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SECURITY_OAUTH2_ISSUER}
spring.jpa.hibernate.ddl-auto=validate
spring.grpc.server.port=9091
