spring.application.name=userservice
server.port=8081
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SECURITY_OAUTH2_JWKSET:http://authservice:9000/oauth2/jwks}
spring.jpa.hibernate.ddl-auto=validate
spring.grpc.server.port=9091

security.oauth2.expected-issuer=${SECURITY_OAUTH2_ISSUER:http://auth.localhost}
