spring.application.name=authservice
server.port=9000
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.oauth2=INFO
auth.client-secret=secret
auth.demo-password=demo
auth.jwk-file=jwk.json
security.oauth2.issuer=http://127.0.0.1:9000
