spring.application.name=authservice
server.port=9000
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.oauth2=INFO
auth.client-secret=${AUTH_CLIENT_SECRET:}
auth.jwk-file=jwk.json
security.oauth2.issuer=${SECURITY_OAUTH2_ISSUER:}
userservice.url=${USERSERVICE_URL:http://localhost:8081/users/auth}
auth.redirect-uri=${AUTH_REDIRECT_URI:http://localhost:8080/login/oauth2/code/authservice}
public.app.url=${PUBLIC_APP_URL:http://app.localhost}
