spring.application.name=messageservice
server.port=8082
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SECURITY_OAUTH2_ISSUER}
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.grpc.client.channels.userservice.address=localhost:9091
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.grpc.server.port=-1
