spring.application.name=messageservice
server.port=8082
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SECURITY_OAUTH2_JWKSET:http://authservice:9000/oauth2/jwks}
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.grpc.client.channels.userservice.address=${USERSERVICE_GRPC_ADDRESS:localhost:9091}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.grpc.server.port=-1
