spring.application.name=bff
server.port=8080

spring.security.oauth2.client.provider.authservice.issuer-uri=${SECURITY_OAUTH2_ISSUER:http://127.0.0.1:9000}
spring.security.oauth2.client.registration.authservice.client-id=gateway-client
spring.security.oauth2.client.registration.authservice.client-secret=${AUTHSERVICE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.authservice.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.authservice.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.authservice.scope=user.read,openid

services.user-service.url=http://localhost:8081
services.message-service.url=http://localhost:8082
