spring.application.name=bff
server.port=8080

spring.security.oauth2.client.provider.authservice.authorization-uri=${AUTH_AUTHORIZATION_URI:http://127.0.0.1:9000}/oauth2/authorize
spring.security.oauth2.client.provider.authservice.token-uri=${AUTH_TOKEN_URI:http://127.0.0.1:9000}/oauth2/token
spring.security.oauth2.client.provider.authservice.jwk-set-uri=${AUTH_JWK_SET_URI:http://127.0.0.1:9000}/oauth2/jwks
spring.security.oauth2.client.provider.authservice.user-info-uri=${AUTH_USER_INFO_URI:http://127.0.0.1:9000}/userinfo

spring.security.oauth2.client.registration.authservice.client-id=gateway-client
spring.security.oauth2.client.registration.authservice.client-secret=${AUTHSERVICE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.authservice.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.authservice.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.authservice.scope=user.read,openid

services.user-service.url=${USER_SERVICE_URL:http://localhost:8081}
services.message-service.url=${MESSAGE_SERVICE_URL:http://localhost:8082}
spring.security.oauth2.client.provider.authservice.user-name-attribute=sub
